name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setting up build version
        run: |
          version=$(date +'%Y.%m.%d')
          echo "BUILD_VERSION=$version" >> $GITHUB_ENV
          echo "VERSION=$version" >> $GITHUB_ENV
          
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 10.0.x
      - name: Analyze Code with Azure OpenAI
        uses: anuraj/code-analysis@v1
        with:
          repository: ${{ github.repository }}
          azure_openai_endpoint: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
          azure_openai_key: ${{ secrets.AZURE_OPENAI_KEY }}
          azure_openai_deployment: 'gpt-5-nano'
      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Build the NuGet package
        run: dotnet pack --configuration Release --output ${{github.workspace}}\Package /p:PackageVersion=${{ env.VERSION }}

      - name: Publish NuGet Package
        run: dotnet nuget push ${{ github.workspace }}\Package\*.nupkg --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json
        
